"""Native 0x411270 CPU records and input-history synthesis (VP executable)."""
import json
import re
import struct

DIRECTIONS = (0, 0, 2, 10, 8, 9, 1, 5, 4, 6, 1, 4, 2, 8, 0, 0)


def entries(table):
    depth = 0
    for i, c in enumerate(table):
        if c == '{':
            depth += 1
            if depth == 2: start = i
        elif c == '}':
            if depth == 2: yield table[start:i+1]
            depth -= 1


def names(table):
    return [json.loads(re.search(r'name = ("(?:[^"\\]|\\.)*")', e)[1])
            for e in entries(table)]


def locate(raw, labels, stride):
    encoded = [s.encode('cp932') for s in labels]
    at = raw.find(encoded[0] + b'\0')
    while at >= 0:
        if all(raw[at+i*stride:at+i*stride+32].split(b'\0',1)[0] == s
               for i, s in enumerate(encoded)):
            return at
        at = raw.find(encoded[0] + b'\0', at+1)
    raise ValueError('Native CPU/command table not found')


def command_history(record):
    # Newest first. Native walks all ten command slots backwards.
    masks = struct.unpack_from('<10H', record, 42)
    amounts = struct.unpack_from('<10H', record, 62)
    result = []
    for mask, amount in reversed(list(zip(masks, amounts))):
        if not mask & 0x2000: continue
        value = DIRECTIONS[mask & 15] | (mask & 0x3f0)
        mode = mask >> 14
        if mode == 0: result.append(value)
        elif mode == 1: result.extend([-1, value] * amount)
        elif mode == 2: result.extend([value] * amount)
        else: result.extend([value | d for d in (2, 8, 1, 4)] * amount)
    if len(result) > 1024:
        raise ValueError('Command wraps the native history ring; implement before exporting')
    return result


def export_cpu(source, commands, cpu, destination):
    raw = source.read_bytes()
    command_names, cpu_names = names(commands), names(cpu)
    command_at = locate(raw, command_names, 82)
    cpu_at = locate(raw, cpu_names, 111)
    # Parsed metadata omits trailing empty registrations; native scans all 100.
    histories = [[]] + [command_history(raw[command_at+i*82:command_at+(i+1)*82])
                        for i in range(len(command_names))]
    lines = ['# Native CPU records and synthesized command history; generated by cpu_data.py.',
             'commands = {']
    lines += ['    { ' + ', '.join(map(str,h)) + ' },' for h in histories]
    lines += ['},', 'patterns = {']
    for i in range(100):
        record = raw[cpu_at+i*111:cpu_at+(i+1)*111]
        flags, probability, near, far = struct.unpack_from('<BBHH',record,32)
        steps = []
        for j in range(10):
            mask, command, amount = struct.unpack_from('<HHH', record,42+7*j)
            if mask & 0x2000: assert command < len(histories)
            steps.append('{ command = %d, amount = %d, direction = %d, active = %s }' %
                         (command, amount, mask & 15, 'true^' if mask & 0x2000 else 'false^'))
        lines.append('    { probability = %d, near = %d, far = %d, air = %s, enemyAir = %s, steps = { %s } },' %
                     (probability,near,far,'true^' if flags & 1 else 'false^',
                      'true^' if flags & 2 else 'false^',', '.join(steps)))
    lines.append('},')
    destination.write_text('\n'.join(lines)+'\n',encoding='utf-8', newline='\n')

