"""Compile independent support namespaces from normalized conversion data.

Runtime handles reserve 10000 slots per namespace. The character keeps its own
FM2K IDs; no compatibility slots for support bodies are emitted into it.
"""
from copy import deepcopy
import re
from layout import conversion_path

BANKS = {'えこ': 10000, 'シエラ': 20000, 'ジュリエット': 30000,
         'かなえ': 40000, 'ヒルダ': 50000, 'common': 60000}


def ref_positions(b):
    if b[0] == 'V':
        return [7] if b[5] else []
    # R/RP operands index reaction tables, not skills.
    if b[0] == 'O':
        return [1, 7]
    return {'SG': [1], 'SC': [1], 'SF': [1], 'Rnd': [3], 'COM': [2],
            'GL': [3], 'GS': [4], 'DS': [1], 'C': [3], 'DB': [4]}.get(b[0], [])


def relocate(skill, mapping):
    out = deepcopy(skill)
    for b in out['blocks']:
        for k in ref_positions(b):
            if b[k] > 0:
                b[k] = mapping.get(b[k], b[k])
    return out


def emit(skill, number, space='', media=''):
    # Import lazily: share_supports calls this module after normalization.
    from share_supports import skill_text
    from gen_script import lton_str
    return skill_text(skill).replace('blocks = {',
        f'id = {number}, space = {lton_str(space)}, media = {lton_str(media)}, blocks = {{', 1)


def compile_namespaces(root, reference, groups, normalized, mappings, outputs):
    from share_supports import recipe_for, reference_text
    canonical_ids = {n: BANKS[space] + i for space, ids in groups.items() for i, n in enumerate(ids)}
    models = {canonical_ids[n]: relocate(reference[n], canonical_ids) for n in canonical_ids}
    for space, ids in groups.items():
        header = f'# Independent support skills; generated by share_supports.py.\nnamespaceBase = {BANKS[space]},\n'
        path = root / 'supports' / space / 'script.lton'
        outputs[conversion_path(path.with_name('support-source.lton'))] = outputs[path]
        outputs[path] = header + ''.join(
            emit(models[canonical_ids[n]], i, space, 'assets/supports/common') for i, n in enumerate(ids))
    stats = {}
    for character, skills in normalized.items():
        path = root / 'characters' / character / 'script.lton'
        # Retain a reproducible conversion intermediate, never used by runtime.
        source = outputs[path]
        outputs[conversion_path(path.with_name('support-source.lton'))] = source
        header = re.split(r'(?m)^\{ name = ', source, maxsplit=1)[0]
        remap = {local: canonical_ids[n] for n, local in mappings[character].items()}
        owners, overrides = [], []
        for i, sk in enumerate(skills):
            linked = relocate(sk, remap)
            if i not in remap:
                owners.append(emit(linked, i))
            else:
                handle = remap[i]
                if linked['blocks'] != models[handle]['blocks'] or linked['level'] != models[handle]['level']:
                    if character != 'くるみ':
                        raise ValueError(f'Unexpected namespace override: {character}/{i}')
                    space = next(s for s, base in BANKS.items() if base <= handle < base + 10000)
                    recipe, changes = recipe_for(models[handle]['blocks'], linked['blocks'])
                    patch = reference_text(linked, space, handle - BANKS[space], recipe, changes)
                    overrides.append(patch.replace('blocks = {', f'id = {handle}, blocks = {{', 1))
        outputs[path] = header + 'supportNamespaces = true^,\n' + ''.join(owners + overrides)
        stats[character] = {'owner_skills': len(owners), 'collaboration_overrides': len(overrides)}
    return stats
