"""Generate winner-only media lists for the shared victory demo.

Opponent and random branches remain unknown: include every candidate.
Usage: python victory_media.py assets/demos/ゆい勝ち
"""
import argparse
from pathlib import Path
from layout import metadata_path

from supports import read_skills


def collect(skills, winner=None):
    # Match vp.script.layers: every named nonempty skill except slot zero.
    todo = [(n, 0) for n, s in enumerate(skills)
            if n >= 1 and s['name'] and s['blocks']]
    seen, images, sounds = set(), set(), set()
    # This is deliberately restricted to the victory demo's instruction set.
    # New control-flow instructions must not silently become fallthroughs.
    allowed = {'Settings', 'COLOR', 'I', 'S', 'V', 'Rnd', 'SG', 'E'}
    for s in skills:
        for b in s['blocks']:
            if b[0] not in allowed:
                raise ValueError(f'Unsupported victory instruction: {b[0]}')
            if b[0] == 'V' and b[1] == 129 and b[2] != 0:
                raise ValueError('Victory script modifies winner variable 129')
    while todo:
        s, at = todo.pop()
        if (s, at) in seen:
            continue
        if not 0 <= s < len(skills) or at < 0:
            raise ValueError(f'Invalid victory target: {s}:{at}')
        seen.add((s, at))
        blocks = skills[s]['blocks']
        if at >= len(blocks):
            # Demo layers loop at the end of a skill.
            if blocks:
                todo.append((s, 0))
            continue
        b = blocks[at]
        op = b[0]
        if op == 'E':
            continue
        if op in ('I', 'S') and b[1] >= 0:
            (images if op == 'I' else sounds).add(b[1])
        if op == 'SG' and b[1] >= 0:
            todo.append((b[1], b[2]))
            continue
        if op == 'V' and b[5] > 0 and b[7] >= 0:
            hit = None
            if b[1] == 129 and winner is not None:
                hit = winner == b[6] if b[5] == 1 else winner > b[6] if b[5] == 2 else winner < b[6]
            if hit is not False:
                todo.append((b[7], b[8]))
            if hit is True:
                continue
        if op == 'Rnd' and b[3] >= 0:
            todo.append((b[3], b[4]))
        todo.append((s, at + 1))
    return sorted(images), sorted(sounds)


def generate(directory):
    directory = metadata_path(directory)
    skills = read_skills(directory / 'script.lton')
    lines = ['# Generated by victory_media.py. Opponent and random branches include all candidates.']
    for winner in range(100, 1001, 100):
        images, sounds = collect(skills, winner)
        nums = lambda xs: '{ ' + ', '.join(map(str, xs)) + ' }'
        lines.append(f'{{ winner = {winner}, images = {nums(images)}, sounds = {nums(sounds)} }},')
    path = directory / 'preload.lton'
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    return path


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory', type=Path)
    print(generate(parser.parse_args().directory))
